import React, { useState, useMemo, useEffect } from 'react';
import { Search, RefreshCw, Building2, Download, Loader2 } from 'lucide-react';
import { OpenDatasetItem } from '../../types';
import { api } from '../../services/api';
interface Props { loading: boolean; onImport: (url: string)=>void; onError: (m:string)=>void; }
const TAGS=['Todos','Economía','Movilidad','Población','Ventas','Medioambiente'] as const;
export const OpenDataExplorer: React.FC<Props> = ({ loading, onImport, onError }) => {
  const [q,setQ]=useState(''); const [results,setResults]=useState<OpenDatasetItem[]>([]); const [tag,setTag]=useState('Todos'); const [busy,setBusy]=useState(false);
  useEffect(()=>{ api.getFeaturedOpenDatasets().then(setResults).catch(()=>{}); },[]);
  const filtered=useMemo(()=> tag==='Todos'?results:results.filter(i=>i.tags.some(t=>t.toLowerCase().includes(tag.toLowerCase()))),[results,tag]);
  const search=async(e?:React.FormEvent)=>{ if(e) e.preventDefault(); setBusy(true); try{ const r=await api.searchOpenDatasets(q,12); setResults(r.results||[]);}catch(err:unknown){ onError(err instanceof Error?err.message:'Error en Open Data');}finally{ setBusy(false);} };
  return (<div style={{padding:'8px 0'}}><form onSubmit={search} style={{marginBottom:'16px'}}><div style={{display:'flex',gap:'10px',flexWrap:'wrap'}}><div style={{position:'relative',flex:1,minWidth:'260px'}}><div style={{position:'absolute',left:'12px',top:'50%',transform:'translateY(-50%)',color:'var(--text-muted)',pointerEvents:'none'}}><Search size={18} aria-hidden='true'/></div><input type='text' placeholder='Buscar: precios, transporte, energía...' value={q} onChange={(e)=>setQ(e.target.value)} disabled={loading||busy} style={{width:'100%',padding:'10px 14px 10px 38px',backgroundColor:'var(--bg-input)',border:'1px solid var(--border-color)',borderRadius:'8px'}}/></div><button type='submit' className='btn btn-primary' disabled={loading||busy} style={{padding:'10px 20px'}}>{busy?<><Loader2 size={16} className='spin' aria-hidden='true'/> Buscando...</>:<><Search size={16} aria-hidden='true'/> Buscar</>}</button>{q&&<button type='button' className='btn btn-outline' onClick={()=>{setQ(''); api.getFeaturedOpenDatasets().then(setResults);}} disabled={loading||busy}><RefreshCw size={16} aria-hidden='true'/></button>}</div></form><div style={{display:'flex',gap:'8px',flexWrap:'wrap',marginBottom:'16px'}}>{TAGS.map(t=>(<button key={t} type='button' onClick={()=>setTag(t)} style={{fontSize:'0.78rem',padding:'4px 10px',borderRadius:'16px',border:'1px solid',borderColor:tag===t?'var(--primary)':'var(--border-color)',backgroundColor:tag===t?'var(--primary-light)':'var(--bg-input)',color:tag===t?'var(--primary)':'var(--text-muted)',cursor:'pointer',fontWeight:tag===t?700:500}}>{t}</button>))}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit, minmax(280px, 1fr))',gap:'14px'}}>{filtered.length?filtered.map(item=>(<div key={item.id} style={{backgroundColor:'var(--bg-input)',border:'1px solid var(--border-color)',borderRadius:'10px',padding:'16px',display:'flex',flexDirection:'column',gap:'12px'}}><div><div style={{display:'flex',justifyContent:'space-between',marginBottom:'6px'}}><div style={{display:'flex',alignItems:'center',gap:'6px',fontSize:'0.75rem',color:'var(--primary)'}}><Building2 size={14} aria-hidden='true'/><span style={{fontWeight:600}}>{item.organization}</span></div><span className='badge badge-emerald' style={{fontSize:'0.7rem'}}>{item.format}</span></div><h4 style={{fontSize:'0.95rem',fontWeight:700}}>{item.title}</h4><p style={{fontSize:'0.8rem',color:'var(--text-muted)'}}>{item.description}</p></div><button className='btn btn-outline' style={{width:'100%',justifyContent:'center'}} onClick={()=>onImport(item.resource_url)} disabled={loading}><Download size={14} aria-hidden='true'/> Importar a DataFlow</button></div>)):<div style={{padding:'24px',textAlign:'center',color:'var(--text-muted)',gridColumn:'1 / -1'}}>No se encontraron datasets.</div>}</div></div>);
};
