import React, { useState } from 'react';
import { Link2, Download, Loader2, ShieldCheck, ArrowRight } from 'lucide-react';
interface Props { loading: boolean; onImport: (url: string)=>void; }
const EXAMPLES=[{name:"PIB Mundial",desc:"GDP",url:"https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"},{name:"Carsharing",desc:"Movilidad",url:"https://raw.githubusercontent.com/plotly/datasets/master/carshare_data.csv"},{name:"Iris",desc:"Iris",url:"https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"}];
export const UrlImporter: React.FC<Props> = ({ loading, onImport }) => {
  const [u,setU]=useState("");
  const submit=(e?:React.FormEvent)=>{ if(e) e.preventDefault(); const v=u.trim(); if(!v) return; if(!v.startsWith("http://")&&!v.startsWith("https://")) return; onImport(v); };
  return (<div style={{padding:"8px 0"}}><form onSubmit={submit}><div style={{marginBottom:"16px"}}><label htmlFor="urlInputField" style={{display:"block",fontSize:"0.875rem",fontWeight:600,marginBottom:"8px"}}>Enlace directo a CSV o Excel:</label><div style={{display:"flex",gap:"10px",flexWrap:"wrap"}}><div style={{position:"relative",flex:1,minWidth:"260px"}}><div style={{position:"absolute",left:"12px",top:"50%",transform:"translateY(-50%)",color:"var(--text-muted)",pointerEvents:"none"}}><Link2 size={18} aria-hidden="true"/></div><input id="urlInputField" type="url" placeholder="https://raw.githubusercontent.com/.../dataset.csv" value={u} onChange={(e)=>setU(e.target.value)} disabled={loading} style={{width:"100%",padding:"10px 14px 10px 38px",backgroundColor:"var(--bg-input)",border:"1px solid var(--border-color)",borderRadius:"8px"}}/></div><button type="submit" className="btn btn-primary" disabled={loading||!u.trim()} style={{whiteSpace:"nowrap"}}>{loading?<><Loader2 size={16} className="spin" aria-hidden="true"/> Descargando...</>:<><Download size={16} aria-hidden="true"/> Importar</>}</button></div></div></form><div style={{display:"flex",alignItems:"center",gap:"8px",fontSize:"0.78rem",color:"var(--text-muted)",backgroundColor:"rgba(14,165,233,0.05)",padding:"8px 12px",borderRadius:"6px",marginBottom:"16px"}}><ShieldCheck size={16} className="text-primary" aria-hidden="true"/><span>Protegido contra SSRF con IP Pinning y 20 MB max.</span></div><div style={{display:"flex",gap:"8px",flexWrap:"wrap"}}>{EXAMPLES.map((ex,i)=>(<button key={i} type="button" className="btn btn-outline" style={{fontSize:"0.78rem",padding:"6px 12px",borderRadius:"20px"}} onClick={()=>setU(ex.url)} disabled={loading}><span style={{fontWeight:600}}>{ex.name}</span><span style={{color:"var(--text-dim)",marginLeft:"4px"}}>({ex.desc})</span><ArrowRight size={12} aria-hidden="true" style={{marginLeft:"4px"}}/></button>))}</div></div>);
};
